<?php $players = $data['players'] ?>

<h1></h1>
 <?php foreach $players as $value: ?>
    <?php echo
    <section id="party">
        <form class="row g-3" action="?page=contact" method="POST">
        <div class="col-6">
            <label for="firstname" class="form-label">Firstname*</label>
            <input required type="text" class="form-control" id="firstname" name="firstname">
        </div>
        <div class="col-6">
            <label for="lastname" class="form-label">Lastname*</label>
            <input required type="text" class="form-control" id="lastame" name="lastname">
        </div>
        <div class="col-md-6">
            <label for="email" class="form-label">Email*</label>
            <input required type="email" class="form-control" id="email" name="email">
        </div>
        <div class="col-md-6">
            <label for="password" class="form-label">Password*</label>
            <input required type="password" class="form-control" id="password" name="password">
        </div>
        <div class="col-12">
            <label for="address1" class="form-label">Address</label>
            <input type="text" class="form-control" id="address1" name="address1" placeholder="1234 Main St">
        </div>
        <div class="col-12">
            <label for="address2" class="form-label">Address 2</label>
            <input type="text" class="form-control" id="address2" name="address2" placeholder="Apartment, studio, or floor">
        </div>
        <div class="col-md-6">
            <label for="city" class="form-label">City</label>
            <input type="text" class="form-control" id="city" name="city">
        </div>
        <div class="col-md-2">
            <label for="zip" class="form-label">Zip</label>
            <input type="text" class="form-control" id="zip" name="zip">
        </div>

        <div class="col-12">
            <div class="form-check">
            <input required class="form-check-input" type="checkbox" id="accepted" name="accepted">
            <label class="form-check-label" for="accepted">
                I accept the private policy
            </label>
            </div>
        </div>
        <div class="form-floating">
            <textarea class="form-control" placeholder="Leave a comment here" id="message" name="message"></textarea>
        <label for="message">Comments</label>
    </div>
        <div class="col-12 mb-3">
            <button type="submit" class="btn btn-dark">Send</button>
        </div>
        </form
    </section>
    ?>
 <?php endforeach; ?>