<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">
    <link rel="stylesheet" href="./src/assets/css/main.css">
    <title>PHP Object !</title>
</head>
<body>
    <header>

<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
<div class="container-fluid">
<a class="navbar-brand" href="#" ><img src="./assets/logo/flight.png" style="width: 50px;"/></a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
      <a class="nav-link <?php if($page === 'home') echo "active"; ?>" href="?page=home">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link <?php  if($page === 'gallery') echo "active"; ?>" href="?page=gallery">Gallery</a>
    </li>
    <li class="nav-item">
      <?php if (!isset ($_SESSION['user'])): ?>
      <a class="nav-link <?php  if($page === 'contact') echo "active"; ?>" href="?page=contact">
        Contact
      </a>
      <?php endif; ?>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Account
      </a>
      <ul class="dropdown-menu">
        
        <!-- <?php if (isset($_SESSION['user']['roles']) && in_array("ROLE_ADMIN",json_decode($_SESSION['user']['roles']))): ?> -->
            <!-- rmettre le code plus haut et virer utils si pas de solution. remettre en service le endif -->
            <?php if (App\Services\Utils::isRole("ROLE_ADMIN")) ?>
                <li><a class="dropdown-item" href="?page=admin">Admin</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a href="?page=profil" class="dropdown-item">Profil</a></li>
                
        <!-- <?php endif; ?> -->
        
        <?php if (!isset($_SESSION['user'])): ?>
        <li><a class="dropdown-item" href="?page=login">login</a></li>
        <?php else: ?>
        <li><a class="dropdown-item" href="?page=logout">Logout</a></li>
        <?php endif; ?>
        <!-- <li><a class="dropdown-item" href="#">Another action</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li> -->
      </ul>
    </li>

  </ul>
  <form class="d-flex" role="search">
    <input name="page" value="search" type="hidden">
    <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>


      <?php if (isset($_SESSION['user']['roles']) && in_array("ROLE_ADMIN",json_decode($_SESSION['user']['roles']))): ?> 
        
          <button class="btn btn-outline-warning perso">
            <a class="nav-link" href="?page=admin">
              Admin   
            </a>
          </button>
          
        <?php endif; ?>



</div>
</div>
</nav>

</header>

<!-- main -->
<main class="container">

    <?= $template; ?>

</main>

<footer  class="bg-dark text-white text-center p-2">
    <p>
        &copy; cci unlimited
    </p>
</footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"  crossorigin="anonymous"></script>
</body>
</html>