<h1>Profil</h1>
<h3>Bienvenue sur votre page de profil <strong class="text-info"><?= $user['firstname']?> <?= $user['lastname'] ?></strong></h3>
<form class="row g-3" action="?page=profil&action=profilupdate" method="POST">
        <!-- <div>
            <label for="avatar" class="form-label">Avatar</label>
            <input type="img" class="form-control" id="avatar" name="avatar" value="<?= $user['avatar'] ?>">
        </div> -->
        <div class="col-6">
            <label for="firstname" class="form-label">Firstname</label>
            <input required type="text" class="form-control" id="firstname" name="firstname" value="<?= $user['firstname'] ?>">
        </div>
        <div class="col-6">
            <label for="lastname" class="form-label">Lastname</label>
            <input required type="text" class="form-control" id="lastame" name="lastname" value="<?= $user['lastname'] ?>">
        </div>
        <div class="col-md-6">
            <label for="email" class="form-label">Email</label>
            <input required type="email" class="form-control" id="email" name="email" value="<?= $user['email'] ?>">
        </div>
        <!-- <div class="col-md-6">
            <label for="password" class="form-label">Password</label>
            <input required type="password" class="form-control" id="password" name="password">
        </div> -->
        <div class="col-12">
            <label for="address1" class="form-label">Address</label>
            <input type="text" class="form-control" id="address1" name="address1" value="<?= $user['address1'] ?>">
        </div>
        <div class="col-12">
            <label for="address2" class="form-label">Address 2</label>
            <input type="text" class="form-control" id="address2" name="address2"value="<?= $user['address2'] ?>">
        </div>
        <div class="col-md-6">
            <label for="city" class="form-label">City</label>
            <input type="text" class="form-control" id="city" name="city" value="<?= $user['city'] ?>">
        </div>
        <div class="col-md-4">
            <label for="state" class="form-label">State</label>
            <select id="state" name="state" class="form-select" value="<?= $user['state'] ?>">
            <option selected><?= $user['state'] ?></option>
            <?php foreach ($state as $value): ?>
            <option> <?= $value ?> </option>
            <?php endforeach; ?>
            </select>
        </div>
        <div class="col-md-2">
            <label for="zip" class="form-label">Zip</label>
            <input type="text" class="form-control" id="zip" name="zip" value="<?= $user['zip'] ?>">
        </div>
        <div class="col-12 mb-3">
            <button type="submit" name="submit" class="btn btn-dark">Update my profil</button>
        </div>
        
</form>