<h1>Add a new User</h1>
    <section id="accounts">

    <?php if (isset($errors) && !empty($errors)): ?>
        <?php foreach ($errors as $error): ?>
                <div class="alert alert-danger" role="alert">
                    <?= $error; ?>
                </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($isDone): ?>
        <div class="alert alert-success" role="alert">
            <p>Le compte <?=$email ?> a été créé avec succès</p>
        </div>
    <?php else: ?>

    <form class="row g-3" action="?page=adminaccountsadd" method="POST">
            <div class="col-6">
                <label for="firstname" class="form-label">Firstname*</label>
                <input required type="text" class="form-control" id="firstname" name="firstname">
            </div>
            <div class="col-6">
                <label for="lastname" class="form-label">Lastname*</label>
                <input required type="text" class="form-control" id="lastame" name="lastname">
            </div>
            <div class="col-md-6">
                <label for="email" class="form-label">Email*</label>
                <input required type="email" class="form-control" id="email" name="email">
            </div>
            <div class="col-md-6">
                <label for="password" class="form-label">Password*</label>
                <input required type="password" class="form-control" id="password" name="password">
            </div>
            <div class="col-12">
                <label for="address1" class="form-label">Address</label>
                <input type="text" class="form-control" id="address1" name="address1" placeholder="1234 Main St">
            </div>
            <div class="col-12">
                <label for="address2" class="form-label">Address 2</label>
                <input type="text" class="form-control" id="address2" name="address2" placeholder="Apartment, studio, or floor">
            </div>
            <div class="col-md-6">
                <label for="city" class="form-label">City</label>
                <input type="text" class="form-control" id="city" name="city">
            </div>
            <div class="col-md-4">
                <label for="state" class="form-label">State</label>
                <select id="state" name="state" class="form-select">
                <option selected>Choose...</option>
                <?php foreach ($state as $value): ?>
                <option> <?= $value ?> </option>
                <?php endforeach; ?>
                </select>
            </div>
            <div class="col-md-2">
                <label for="zip" class="form-label">Zip</label>
                <input type="text" class="form-control" id="zip" name="zip">
            </div>
            <div>
                <legend>Roles</legend>
                <div>
                    <input type="radio" id="member" name="roles" value="member" checked>
                    <label for="member">Member</label>
                </div>
                <div>
                    <input type="radio" id="admin" name="roles" value="admin">
                    <label for="admin">Admin</label>
                </div>
                
            </div>
            <div class="col-12 mb-3">
                <button type="submit" class="btn btn-dark">Send</button>
            </div>
                </form>
    <?php endif; ?>
    </section>