<h1>Page de Détail</h1>
<section id="gallery" class="row">

    <article class="">
        <div class="">
            <img src="<?php echo $post['image']; ?>" class="" alt="<?php echo $posts['title']; ?>">
                <div class="">
                <h5 class=""><?php echo $post['title']; ?></h5>
                <p class=""><?= (strlen($post['description']) > 60) ? substr($posts['description'],0,57).'...' : $post['description']; ?></p>
                <span class="badge text-bg-light">Author: <strong><?php echo $post['firstname']; ?> <?php echo $post['lastname']; ?></strong></span>
                <span class="badge text-bg-light">Posted on: <strong><?= $post['created_at'] ?></strong></span>
                <?php foreach ($existing_articles as $article): ?>
                <p><?= $article['article'] ?></p>
                <?php endforeach; ?>
                
            </div>
        </div>
    </article>
    <div>
        <h3>Comments</h3>
        <?php foreach($existing_comments as $comment):?>
            <span><?= $comment['firstname'] ?> <?= $comment['lastname'] ?></span>
            <p><?= $comment['comment']?></p>
        <?php endforeach; ?>
    </div>
    <form action="" method="POST">
        <div class="form-floating">
        <textarea class="form-control" placeholder="Leave a comment here" id="comment" name="comment" style="height: 100px"></textarea>
        <label for="comment">Comments</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</section>
