<h1>Admin Dashboard</h1>
<p class="bg-light">Welcome to the Dashboard <span class="text-success"><strong><?= $_SESSION['user']['firstname'];?> <?= $_SESSION['user']['lastname'];?></strong></span> </p>

<h2>Accounts overview</h2>

<p><a class="btn btn-success" href="?page=admin_accounts_add" role="button">Add a new User</a></p>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Email</th>
      <th scope="col">Roles</th>
      <th scope="col">Registered_at</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($users as $user): ?>
      <tr>
        <th scope="row"><?= $user['id'] ?></th>
        <td><?= $user['email'] ?></td>
        <td><?= $user['roles'] ?></td>
        <td><?= $user['registered_at'] ?>...</td>
        <td><a class="btn btn-warning mb-2" href="javascript:updateUser(<?= $user['id']?>)" role="button">Update</a>
        <br>
        <a class="btn btn-danger mb-2" href="javascript:deleteUser(<?= $user['id']?>)" role="button">Delete</a></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
<p><a class="btn btn-success" href="?page=admin_post_add" role="button">Add a new Post</a></p>
<script>
  function deleteUser(id){
    const question = window.confirm("Are you sure to delete the post "+id+" ?");
    if (question) {
      location.href="?page=admin_accounts_delete&id="+id;
    }
  }

  function updateUser(id){
      location.href="?page=admin_accounts_update&id="+id;
  }
</script>