<h1>Update user</h1>
    <section id="accounts"></section>
    <form class="row g-3" action="?page=admin_accounts_update&id=<?= $user['id']?>" method="POST">
            <div class="col-6">
                <label for="firstname" class="form-label">Firstname*</label>
                <input required type="text" class="form-control" id="firstname" name="firstname" value="<?= $user['firstname']?>" 
            </div>
            <div class="col-6">
                <label for="lastname" class="form-label">Lastname*</label>
                <input required type="text" class="form-control" id="lastame" name="lastname" value="<?= $user['lastname']?>">
            </div>
            <div class="col-md-6">
                <label for="email" class="form-label">Email*</label>
                <input required type="email" class="form-control" id="email" name="email" value="<?= $user['email']?>">
            </div>
            <div class="col-12">
                <label for="address1" class="form-label">Address</label>
                <input type="text" class="form-control" id="address1" name="address1" value="<?= $user['address1']?>">
            </div>
            <div class="col-12">
                <label for="address2" class="form-label">Address 2</label>
                <input type="text" class="form-control" id="address2" name="address2" value="<?= $user['address2']?>">
            </div>
            <div class="col-md-6">
                <label for="city" class="form-label">City</label>
                <input type="text" class="form-control" id="city" name="city" value="<?= $user['city']?>">
            </div>
            <div class="col-md-4">
                <label for="state" class="form-label">State</label>
                <select id="state" name="state" class="form-select">
                <option selected><?= $user['state']?></option>
                <?php foreach ($state as $value): ?>
                <option> <?= $value ?> </option>
                <?php endforeach; ?>
                </select>
            </div>
            <div class="col-md-2">
                <label for="zip" class="form-label">Zip</label>
                <input type="text" class="form-control" id="zip" name="zip" value="<?= $user['zip']?>">
            </div>
            <div>
                <legend>Actuals roles : <?= $user_role ?></legend>
                <div>Want to change roles ?</div>
                <div>
                    <div>
                        <input type="radio" id="member" name="roles" value="member">
                        <label for="member">Member</label>
                    </div>
                    <div>
                        <input type="radio" id="admin" name="roles" value="admin">
                        <label for="admin">Admin</label>
                    </div>
                </div>
            </div>
            <div class="col-12 mb-3">
                <button type="submit" class="btn btn-dark">Actualize</button>
            </div>
            </form>
            <script>
                      function toggle(ajout){
        
            doc = document.getElementById('button-admin');
            doc.classList.toggle('hidden');
        }
    
            </script>
      