<h1><?= CONFIG_SITE_TITLE?></h1>
<?php if (isset($_SESSION['user']['roles']) && in_array("ROLE_MEMBER",json_decode($_SESSION['user']['roles']))): ?>
  <p>Welcome dear <span class="text-success"><strong><?= $_SESSION['user']['firstname'];?> <?= $_SESSION['user']['lastname'];?></strong></span> !</p>
<?php endif; ?>
<!-- carousel dynamique -->
<div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>

  <div class="carousel-inner">
<!-- debut boucle foreach -->
    <?php
    foreach($posts as $key => $article):
    ?>
<!-- code permettant d'éviter d'avoir plusieurs "active" à cause du foreach, si la clé est la première du tableau, elle est active -->
    <div class="carousel-item <?php if ($key === array_key_first($posts)) echo "active" ?>">
      <img src="<?= $article['image'] ?>" class="d-block w-100" alt="<?= $article['title'] ?>">
      <div class="carousel-caption d-none d-md-block">
        <h5><?= $article['title'] ?></h5>
        <p><?= $article['description'] ?></p>
      </div>
    </div>
<!-- ici ca fonctionne car nos button du haut sont calibrés à 3, correpondant aux 3 images que l'on appelle -->
    <?php
    endforeach;
    ?>
<!-- fin boucle foreach -->
    </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<h2>Home</h2>
<p><?= CONFIG_SITE_SLOGAN ?></p>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut veniam quasi reprehenderit impedit a iusto incidunt, consectetur eos laudantium alias, facilis similique. Inventore cumque assumenda nisi ipsum minima commodi placeat.</p>

