<h1>Page de Détail</h1>
<section id="gallery" class="row">

    <article class="">
        
        <div class="container">
            <?php foreach($files_ordered as $file): ?>
            <p class="">
            <?php if ((isset($file['image'])) && !empty($file['image'])): ?> 
            <img class="img-thumbnail" src="<?= urldecode($file['image'])?>" alt="" />
            <?php else: echo $file['article']; endif?>
            </p>
            <?php endforeach; ?>
        </div>
    </article>
    <div>
        <h3>Comments</h3>
        <?php foreach($existing_comments as $comment):?>
            <span><?= $comment['firstname'] ?> <?= $comment['lastname'] ?></span>
            <p><?= $comment['comment']?></p>
        <?php endforeach; ?>
    </div>
    <?php if (isRole("ROLE_MEMBER")): ?>
    <form action="" method="POST">
        <div class="form-floating">
        <textarea class="form-control" placeholder="Leave a comment here" id="comment" name="comment" style="height: 100px"></textarea>
        <label for="comment">Leave a comments</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <?php else: ?>
        <p>Please <a href="?page=login">login</a> to comment</p>
    <?php endif; ?>

</section>
